---
title: "The exprso Cheatsheet"
author: "Thomas Quinn"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{The exprso Cheatsheet}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Available split methods

## Available fs methods

```{r, echo = FALSE}
df.fs <- data.frame(
  
  "Method" = c("fsSample", "fsNULL", "fsANOVA", "fsStats", "fsPrcomp", "fsPathClassRFE", "fsEbayes", "fsMrmre"),
  "Data" = c(rep("Binary/Multi", 3), rep("Binary", 5)),
  "Notes" = c(rep("Default use", 3), "Use 'how' to select test", rep("Default use", 4)),
  "Details" = c("See stats::sample", "No additional arguments", "See stats::aov", "See stats::t.test or stats::ks.test", "See stats::prcomp", "See pathClass::fit.rfe", "See limma::ebayes", "See mRMRe::mRMR.classic")
)

knitr::kable(df.fs)
```

## Available build methods

```{r, echo = FALSE}
df.build <- data.frame(
  
  "Method" = c("buildNB", "buildLDA", "buildSVM", "buildANN", "buildRF", "buildDNN"),
  "Data" = rep("Binary/Multi", 6),
  "Notes" = c(rep("Default use", 5), "Use h2o::h2o.shutdown() to clear RAM"),
  "Details" = rep("NA", 6)
)

knitr::kable(df.build)
```

## Available pl methods
